## YAML Template.
---
app1:
    image: prueba/demo
    
app2:
    image: prueba/demo
     
nginx:
    image: nginx:alpine
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
        - app1
        - app2
    ports:
        - 80:80